name: CI image build
on:
  push:
    branches:
      - "master"
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        id: tagname
        run: echo "::set-output name=timestamp::$(date +'%s')"
        
      - name: Check out the repository
        uses: actions/checkout@v3
